export const DELETE_TRANSCRIPT_ERROR_TITLE = 'Failed to delete transcript'
export const DELETE_TRANSCRIPT_ERROR_DESCRIPTION = 'Please try again.'
export const DELETE_TRANSCRIPT_ERROR_MESSAGE =
  `${DELETE_TRANSCRIPT_ERROR_TITLE}. ${DELETE_TRANSCRIPT_ERROR_DESCRIPTION}`
